apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: ansible-builder-example
spec:
  source:
    type: Git
    git:
      url: https://github.com/sabre1041/ansible-builder-shipwright
      revision: main
    contextDir: example-builder
  output:
    image: image-registry.openshift-image-registry.svc:5000/ansible-builder-shipwright/ansible-builder-shipwright-example-ee:latest
  strategy:
    name: ansible-builder
    kind: ClusterBuildStrategy
