apiVersion: shipwright.io/v1beta1
kind: ClusterBuildStrategy
metadata:
  name: ansible-builder
  annotations:
    io.kubernetes.cri-o.Devices: "/dev/fuse"
spec:
  steps:
    - args:
        - /bin/bash
        - -c
        - |
          set -e

          # Change into directory containing EE
          cd $(params.shp-source-context)

          # Create Ansible Build Context
          /usr/bin/ansible-builder create -c $HOME/context

          # Build the EE
          /usr/bin/buildah build -t $(params.shp-output-image) $HOME/context

          # Push the EE
          /usr/bin/buildah push --tls-verify=false $(params.shp-output-image)
      image: "quay.io/ablock/ansible-builder-nested:latest"
      name: ansible-builder-build
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        capabilities:
          add:
          - "SETUID"
          - "SETGID"
      workingDir: /workspace/source
