kind: ClusterRole
apiVersion: authorization.openshift.io/v1
metadata:
  name: 'system:openshift:scc:rootless-builds'
rules:
  - verbs:
      - use
    attributeRestrictions: null
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - rootless-builds
